apiVersion: v1
kind: Service
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: joomla
    tier: frontend 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-joomla
  labels:
    app: joomla
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  selector:
    matchLabels:
      app: joomla
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla
        tier: frontend
    spec:
      containers:
      - image: joomla
        name: joomla
        env:
        - name: JOOMLA_DB_HOST
          value: joomla-mysql
        - name: JOOMLA_DB_USER
          value: saurabh
        - name: JOOMLA_DB_NAME
          value: joomla
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: joomla
        volumeMounts:
        - name: joomla-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: joomla-persistent-storage
        persistentVolumeClaim:
          claimName: ebs-joomla