apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
  - upass=redhat
resources:
  - mysql-deployment.yml
  - joomla-deployment.yml